# Generated by Django 3.1.4 on 2020-12-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vj7', '0002_remove_person_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='projection',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seatNumber',
            field=models.PositiveIntegerField(),
        ),
    ]
